// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_gge0Bvg3uBomZma9emBiZIkJI_ZMaNQ',
    appId: '1:630298292008:web:5a7dd6fcadad8c29d4ea1d',
    messagingSenderId: '630298292008',
    projectId: 'expense-tracker-da9e2',
    authDomain: 'expense-tracker-da9e2.firebaseapp.com',
    storageBucket: 'expense-tracker-da9e2.appspot.com',
    measurementId: 'G-90Z4MTYHMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLm6nV7ctj2PP63pXvuLVZNxqOch69d7s',
    appId: '1:630298292008:android:2702bec51f7fd92fd4ea1d',
    messagingSenderId: '630298292008',
    projectId: 'expense-tracker-da9e2',
    storageBucket: 'expense-tracker-da9e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkrhnJi5nfI5WemdRnywEYrXwccke7dVA',
    appId: '1:630298292008:ios:6c00d520ceb66e49d4ea1d',
    messagingSenderId: '630298292008',
    projectId: 'expense-tracker-da9e2',
    storageBucket: 'expense-tracker-da9e2.appspot.com',
    iosBundleId: 'com.example.myExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkrhnJi5nfI5WemdRnywEYrXwccke7dVA',
    appId: '1:630298292008:ios:30d12a5135aba562d4ea1d',
    messagingSenderId: '630298292008',
    projectId: 'expense-tracker-da9e2',
    storageBucket: 'expense-tracker-da9e2.appspot.com',
    iosBundleId: 'com.example.myExpenseTracker.RunnerTests',
  );
}
